# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 935f765dbb424bbcd5a272a414ed7bb59cafb1c0d17bdf463f3e82ccf79075cddbbb443fd30bb4c70141306dcedca4cbefb403560bce60ed7682c5da2ab37b35

test:
  secret_key_base: 7dae717707d642f4260c29f8c7b961bc3c2f69cc496e9da2a2f189ac24aed1120cde3068592ba28867b64e119d213dd9d025a878e5af7838e672a87650f837e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
